name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main/app-py
    path:
      - 'app-py/**'


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1 

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      
      - name: Generate Version Tag
        run: echo "VERSION_TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Build and Tag Docker Image
        run: |
          docker build -t lambda  app-py/.
          docker tag lambda:latest 571600864581.dkr.ecr.ap-south-1.amazonaws.com/lambda:$VERSION_TAG

      - name: Push Docker Image to ECR
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/lambda:$VERSION_TAG

      - name: Update AWS Lambda Function
        run: |
          aws lambda update-function-code \
            --function-name myLambdaFunction \
            --image-uri ${{ steps.login-ecr.outputs.registry }}/lambda:$VERSION_TAG
